
//CREATE PROJECT
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';


//GET PROJECTLIST
export const GET_PROJECT_LIST = 'GET_PROJECT_LIST';
export const GET_PROJECT_LIST_SAGA = 'GET_PROJECT_LIST_SAGA';


//EDIT PROJECT
export const EDIT_PROJECT = 'EDIT_PROJECT';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';

//DELETE PROJECT
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';


//GET PROJECT DETAIL
export const PUT_PROJECT_DETAIL = 'PUT_PROJECT_DETAIL';
export const GET_PROJECT_DETAIL_SAGA = 'GET_PROJECT_DETAIL_SAGA';