export const GET_ALL_TASK_TYPE = 'GET_ALL_TASK_TYPE';
export const GET_ALL_TASK_TYPE_SAGA = 'GET_ALL_TASK_TYPE_SAGA';

export const GET_ALL_TASK_PRIORITY = 'GET_ALL_TASK_PRIORITY';
export const GET_ALL_TASK_PRIORITY_SAGA = 'GET_ALL_TASK_PRIORITY_SAGA';


export const GET_ALL_TASK_STATUS = 'GET_ALL_TASK_STATUS';
export const GET_ALL_TASK_STATUS_SAGA = 'GET_ALL_TASK_STATUS_SAGA';


export const CREATE_NEW_TASK_SAGA = 'CREATE_NEW_TASK_SAGA';


export const GET_TASK_DETAIL = 'GET_TASK_DETAIL';
export const GET_TASK_DETAIL_SAGA = 'GET_TASK_DETAIL_SAGA';


export const UPDATE_STATUS_TASK_SAGA = 'UPDATE_STATUS_TASK_SAGA';


export const CHANGE_TASK_DETAIL_MODAL = 'CHANGE_TASK_DETAIL_MODAL';
export const CHANGE_TASK_ASSIGNESS = 'CHANGE_TASK_ASSIGNESS';
export const REMOVE_USER_ASSIGN = 'REMOVE_USER_ASSIGN';


export const HANDLE_CHANGE_COMBINE_POST_API_UPDATE_TASK = 'HANDLE_CHANGE_COMBINE_POST_API_UPDATE_TASK';